name: 'Nightly Merge'

on:
  push:
    branches: [ develop ]

jobs:
  nightly-merge:

    runs-on: ubuntu-latest

    steps:
    - name: adding github workspace as safe directory
      run: git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Checkout
      uses: actions/checkout@v1

    - name: Nightly Merge
      uses: robotology/gh-action-nightly-merge@v1.3.1
      with:
        stable_branch: 'develop'
        development_branch: 'main'
        allow_ff: false
        allow_forks: true
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_SECRET }}
